[package]
name = "lykkehjul"
version = "0.1.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.31.0"
rand = "0.8.5"
font-kit = "0.11.0"
pathfinder_geometry = "0.5.1"
